### ISSUE TITLE
Does this package generate report for local execution like mochawesome?

### ISSUE THREAD

**Issue by Sathish787** [kristijan-pajtasev/cypress-report#1]
Looks impressive but could not generate report for local execution.
1. Installed cypress-dashboard npm package
2. Modified cypress json file as instructed in Read Me
3. Executed both npx cypress open / npx cypress run (with and without -r cypress-dashboard)

Provide more info on execution side and also if I miss something.

**Comment by kristijan-pajtasev** [comment]
That should be enough, but it generates reports only with the run command. 

I believe you sent a message on Linkedin that you managed to run it, so for now I am closing the issue.
